{{- if .Values.application.autoScaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.application.name }}
  name: {{ .Values.application.name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}-{{ .Release.Name }}
  minReplicas: {{ .Values.autoScaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.autoScaling }}
  metrics:
  {{- if .Values.application.autoScaling.targetCPU }}
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: {{ .Values.autoScaling.targetCPU  }}
  {{- end }}
  {{- if .Values.autoScaling.targetMemory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoScaling.targetMemory  }}
  {{- end }}
{{- end }}