{{- if eq .Values.database.type "external" -}}
apiVersion: v1
metadata:
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.application.name }}
  name: {{ .Values.application.name }}
  namespace: {{ .Release.Namespace }}
kind: Secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.database.external.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.external.password | b64enc | quote }}
{{- end -}}

{{- if eq .Values.database.type "internal" -}}
apiVersion: v1
metadata:
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.application.name }}
  name: {{ .Values.application.name }}
  namespace: {{ .Release.Namespace }}
kind: Secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.database.internal.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.internal.password | b64enc | quote }}
{{- end -}}